# Generated by Django 4.1.2 on 2022-10-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
        ('groups', '0001_initial'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animals',
            new_name='Animal',
        ),
    ]
