# Generated by Django 4.1.2 on 2022-10-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_remove_trait_animals'),
        ('animals', '0002_rename_animals_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='traits',
            field=models.ManyToManyField(related_name='animals', to='traits.trait'),
        ),
    ]
