# Generated by Django 4.1.2 on 2022-10-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_group_animals_alter_group_name_and_more'),
        ('animals', '0003_animal_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='groups.group'),
            preserve_default=False,
        ),
    ]
