# Generated by Django 4.1.2 on 2022-10-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Femea'), ('Não informado', 'Nao Informado')], default='Não informado', max_length=15),
        ),
    ]
