# Generated by Django 4.1.2 on 2022-10-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_group_animals_alter_group_name_and_more'),
        ('animals', '0005_alter_animal_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='groups.group'),
        ),
    ]
