# Generated by Django 4.1.2 on 2022-10-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_alter_animal_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='groups',
            new_name='group',
        ),
    ]
