# Generated by Django 4.1.2 on 2022-10-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_rename_groups_animal_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='group',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='traits',
        ),
    ]
