# Generated by Django 4.1.2 on 2022-10-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_rename_animals_animal'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Traits',
            new_name='Trait',
        ),
    ]
