# Generated by Django 4.1.2 on 2022-10-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_rename_traits_trait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='animals',
        ),
    ]
