# Generated by Django 4.1.2 on 2022-10-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_remove_trait_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
