# Generated by Django 4.1.2 on 2022-10-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('scientific_name', models.CharField(max_length=50)),
                ('animals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='animals.animals')),
            ],
        ),
    ]
