# Generated by Django 4.1.2 on 2022-10-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_traits'),
        ('groups', '0002_alter_group_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='animals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='animals.animal'),
            preserve_default=False,
        ),
    ]
